name: 'Terraform check'
on:
  push:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: queue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3
      - name: Terraform Check
        id: fmt
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt -check --recursive
